// Time zones offered in the settings. Each has its IANA name (used as the
// setting's value), a city to show when no name is given, its standard offset
// from UTC in minutes, and the daylight-saving rule it follows, if any (see
// dst.js).

module.exports = [
  { zone: 'Pacific/Honolulu', city: 'Honolulu', standard: -600 },
  { zone: 'America/Anchorage', city: 'Anchorage', standard: -540, dst: 'US' },
  { zone: 'America/Los_Angeles', city: 'Los Angeles', standard: -480, dst: 'US' },
  { zone: 'America/Vancouver', city: 'Vancouver', standard: -480, dst: 'US' },
  { zone: 'America/Denver', city: 'Denver', standard: -420, dst: 'US' },
  { zone: 'America/Phoenix', city: 'Phoenix', standard: -420 },
  { zone: 'America/Chicago', city: 'Chicago', standard: -360, dst: 'US' },
  { zone: 'America/Mexico_City', city: 'Mexico City', standard: -360 },
  { zone: 'America/New_York', city: 'New York', standard: -300, dst: 'US' },
  { zone: 'America/Toronto', city: 'Toronto', standard: -300, dst: 'US' },
  { zone: 'America/Bogota', city: 'Bogota', standard: -300 },
  { zone: 'America/Halifax', city: 'Halifax', standard: -240, dst: 'US' },
  { zone: 'America/Sao_Paulo', city: 'Sao Paulo', standard: -180 },
  { zone: 'America/Argentina/Buenos_Aires', city: 'Buenos Aires', standard: -180 },
  { zone: 'Atlantic/Reykjavik', city: 'Reykjavik', standard: 0 },
  { zone: 'Europe/London', city: 'London', standard: 0, dst: 'EU' },
  { zone: 'Europe/Lisbon', city: 'Lisbon', standard: 0, dst: 'EU' },
  { zone: 'Europe/Paris', city: 'Paris', standard: 60, dst: 'EU' },
  { zone: 'Europe/Berlin', city: 'Berlin', standard: 60, dst: 'EU' },
  { zone: 'Europe/Madrid', city: 'Madrid', standard: 60, dst: 'EU' },
  { zone: 'Europe/Rome', city: 'Rome', standard: 60, dst: 'EU' },
  { zone: 'Europe/Amsterdam', city: 'Amsterdam', standard: 60, dst: 'EU' },
  { zone: 'Europe/Stockholm', city: 'Stockholm', standard: 60, dst: 'EU' },
  { zone: 'Africa/Lagos', city: 'Lagos', standard: 60 },
  { zone: 'Europe/Athens', city: 'Athens', standard: 120, dst: 'EU' },
  { zone: 'Africa/Cairo', city: 'Cairo', standard: 120, dst: 'EG' },
  { zone: 'Africa/Johannesburg', city: 'Johannesburg', standard: 120 },
  { zone: 'Europe/Istanbul', city: 'Istanbul', standard: 180 },
  { zone: 'Europe/Moscow', city: 'Moscow', standard: 180 },
  { zone: 'Asia/Riyadh', city: 'Riyadh', standard: 180 },
  { zone: 'Africa/Nairobi', city: 'Nairobi', standard: 180 },
  { zone: 'Asia/Tehran', city: 'Tehran', standard: 210 },
  { zone: 'Asia/Dubai', city: 'Dubai', standard: 240 },
  { zone: 'Asia/Karachi', city: 'Karachi', standard: 300 },
  { zone: 'Asia/Kolkata', city: 'Mumbai', standard: 330 },
  { zone: 'Asia/Kathmandu', city: 'Kathmandu', standard: 345 },
  { zone: 'Asia/Dhaka', city: 'Dhaka', standard: 360 },
  { zone: 'Asia/Bangkok', city: 'Bangkok', standard: 420 },
  { zone: 'Asia/Jakarta', city: 'Jakarta', standard: 420 },
  { zone: 'Asia/Singapore', city: 'Singapore', standard: 480 },
  { zone: 'Asia/Hong_Kong', city: 'Hong Kong', standard: 480 },
  { zone: 'Asia/Shanghai', city: 'Shanghai', standard: 480 },
  { zone: 'Australia/Perth', city: 'Perth', standard: 480 },
  { zone: 'Asia/Seoul', city: 'Seoul', standard: 540 },
  { zone: 'Asia/Tokyo', city: 'Tokyo', standard: 540 },
  { zone: 'Australia/Adelaide', city: 'Adelaide', standard: 570, dst: 'AU' },
  { zone: 'Australia/Brisbane', city: 'Brisbane', standard: 600 },
  { zone: 'Australia/Sydney', city: 'Sydney', standard: 600, dst: 'AU' },
  { zone: 'Pacific/Auckland', city: 'Auckland', standard: 720, dst: 'NZ' }
];
