// Generated by tools/make_fonts.py from tools/fonts.json; do not edit.
//
// The bundled font styles, sized to stand in for Pebble's own fonts: for each
// piece of text, the font resource for each style and how far below the top
// of the text box its visible text starts.

#pragma once

#include <pebble.h>

// Style 0 is the face's usual font; the bundled ones follow.
enum { FONT_STYLE_PEBBLE, FONT_STYLE_SERIF, FONT_STYLE_ROUNDED, FONT_STYLE_MONO,
       FONT_STYLE_COUNT };
#define CUSTOM_FONT_COUNT (FONT_STYLE_COUNT - 1)

typedef struct {
  uint32_t resource;
  int8_t pad;
} CustomFont;

// A font in use and where its visible text starts.
typedef struct {
  GFont font;
  int8_t pad;
  bool custom;
} StyledFont;

// Loads the font for a style: Pebble's own font (the usual one, unless the
// face passes its own), or a bundled one.
static inline void styled_font_load(StyledFont *styled, uint8_t style, const char *system_key,
                                    int8_t system_pad, const CustomFont *custom) {
  if (style == FONT_STYLE_PEBBLE || style >= FONT_STYLE_COUNT) {
    *styled = (StyledFont) { fonts_get_system_font(system_key), system_pad, false };
    return;
  }
  const CustomFont *chosen = &custom[style - 1];
  *styled = (StyledFont) {
    fonts_load_custom_font(resource_get_handle(chosen->resource)), chosen->pad, true,
  };
}

static inline void styled_font_unload(StyledFont *styled) {
  if (styled->custom) {
    fonts_unload_custom_font(styled->font);
    styled->custom = false;
  }
}

#if PBL_DISPLAY_WIDTH >= 200
static const CustomFont FONTS_TIME[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_TIME_LARGE_45, 14 },  // Serif 45px
  { RESOURCE_ID_FONT_ROUNDED_TIME_LARGE_44, 13 },  // Rounded 44px
  { RESOURCE_ID_FONT_MONO_TIME_LARGE_44, 13 },  // Mono 44px
};
static const CustomFont FONTS_CITY_TIME[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_CITY_TIME_LARGE_27, 8 },  // Serif 27px
  { RESOURCE_ID_FONT_ROUNDED_CITY_TIME_LARGE_27, 8 },  // Rounded 27px
  { RESOURCE_ID_FONT_MONO_CITY_TIME_LARGE_28, 9 },  // Mono 28px
};
static const CustomFont FONTS_DATE[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_DATE_LARGE_16, 4 },  // Serif 16px
  { RESOURCE_ID_FONT_ROUNDED_DATE_LARGE_17, 5 },  // Rounded 17px
  { RESOURCE_ID_FONT_MONO_DATE_LARGE_17, 5 },  // Mono 17px
};
static const CustomFont FONTS_CITY[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_CITY_LARGE_18, 3 },  // Serif 18px
  { RESOURCE_ID_FONT_ROUNDED_CITY_LARGE_19, 4 },  // Rounded 19px
  { RESOURCE_ID_FONT_MONO_CITY_LARGE_19, 4 },  // Mono 19px
};
static const CustomFont FONTS_DETAIL[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_DETAIL_LARGE_15, 4 },  // Serif 15px
  { RESOURCE_ID_FONT_ROUNDED_DETAIL_LARGE_14, 2 },  // Rounded 14px
  { RESOURCE_ID_FONT_MONO_DETAIL_LARGE_15, 3 },  // Mono 15px
};
#else
static const CustomFont FONTS_TIME[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_TIME_SMALL_37, 11 },  // Serif 37px
  { RESOURCE_ID_FONT_ROUNDED_TIME_SMALL_35, 10 },  // Rounded 35px
  { RESOURCE_ID_FONT_MONO_TIME_SMALL_37, 11 },  // Mono 37px
};
static const CustomFont FONTS_CITY_TIME[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_CITY_TIME_SMALL_20, 6 },  // Serif 20px
  { RESOURCE_ID_FONT_ROUNDED_CITY_TIME_SMALL_19, 6 },  // Rounded 19px
  { RESOURCE_ID_FONT_MONO_CITY_TIME_SMALL_20, 6 },  // Mono 20px
};
static const CustomFont FONTS_DATE[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_DATE_SMALL_14, 4 },  // Serif 14px
  { RESOURCE_ID_FONT_ROUNDED_DATE_SMALL_13, 4 },  // Rounded 13px
  { RESOURCE_ID_FONT_MONO_DATE_SMALL_14, 4 },  // Mono 14px
};
static const CustomFont FONTS_CITY[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_CITY_SMALL_16, 4 },  // Serif 16px
  { RESOURCE_ID_FONT_ROUNDED_CITY_SMALL_17, 5 },  // Rounded 17px
  { RESOURCE_ID_FONT_MONO_CITY_SMALL_17, 5 },  // Mono 17px
};
static const CustomFont FONTS_DETAIL[CUSTOM_FONT_COUNT] = {
  { RESOURCE_ID_FONT_SERIF_DETAIL_SMALL_13, 4 },  // Serif 13px
  { RESOURCE_ID_FONT_ROUNDED_DETAIL_SMALL_12, 3 },  // Rounded 12px
  { RESOURCE_ID_FONT_MONO_DETAIL_SMALL_13, 3 },  // Mono 13px
};
#endif
